name: "gradle-actions"

on:
  release:
    types: [published]
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: gradle version
        run: gradle --version
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Upgrade README.md
        run: sed -i 's/version \".*\"/version "${{ env.RELEASE_VERSION }}"/g' README.md
      - name: Upgrade Gradle.properties
        run: sed -i 's/version=.*/version=${{ env.RELEASE_VERSION }}/g' gradle.properties
      - name: Upgrade Constants.java
        run: sed -i 's/PLUGIN_VERSION = .*/PLUGIN_VERSION = "${{ env.RELEASE_VERSION }}";/g' src/main/java/co/com/bancolombia/Constants.java
      - name: Save version
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: "master"
          commit-message: 'upgrade version to ${{ env.RELEASE_VERSION }}'
          force-add: "true"
          files: README.md gradle.properties src/main/java/co/com/bancolombia/Constants.java
          name: Release Bot
          email: release-bot@bancolombia.com.co
      - name: Publish plugin
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.KEY_GRADLE }} -Pgradle.publish.secret=${{ secrets.SECRET_GRADLE }}
